### ISSUE TITLE
Warning: Error in parse_url: length(url) == 1 is not TRUE

### ISSUE THREAD

**Issue by gcameron89777** [line/conflr#105]
Hi. I tried to post to our company Confluence page yesterday and am experiencing the error above. I'm not sure if it's an issue per se or just unique to my set up, any guidance would be much appreciated.

Duplicate post on rstudio community: https://community.rstudio.com/t/conflr-errors-when-trying-to-publish-a-rmd-page-to-confluence/61832

I have created a Rmd doc and using `output: github_document` I was also able to  generate a readme for a Github repo.

Some folk in our company do not have  access to Github and they wouldlike me to publish the  Rmd documentation of a project to Confluence. I found the https://github.com/line/conflr library for doing this.

I've followed the set up guidelines and added global variables to my .Renviron, including
```
CONFLUENCE_URL="https://confluence.somecompany.com"
CONFLUENCE_USERNAME="doug"
CONFLUENCE_PASSWORD="[my pass]"
```

I then used the conflr add in to attempt to post to a page. I entered the Space of the page which is called 'Analytics' and then the parent page ID (Which I found after clicking on 'page info' in Confluence on the parent page I'd like to post to). After I click publish I get this output in the console:
> No encoding supplied: defaulting to UTF-8.
Listening on http://127.0.0.1:3415
No encoding supplied: defaulting to UTF-8.
No encoding supplied: defaulting to UTF-8.
No encoding supplied: defaulting to UTF-8.
Warning: Error in parse_url: length(url) == 1 is not TRUE
  65: <Anonymous>

I tried Google searching for this error  but did not find anything in relation to it within the context of conflr. How should I interpret this error and how can I overcome it?

I tried some other functions from the package just to see if it recognized by credentials in .Renviron (I restarted R after updating .Renviron with my credentials).

e.g. list pages in a space
```
confl_list_pages(spaceKey = 'Analytics')
No encoding supplied: defaulting to UTF-8.
{html_document}
<html>
[1] <head>\n<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">\n<title>Sign in ・ Cloudflare Access</title ...
[2] <body>\n    <div class="Surface">\n      <div class="AuthBox">\n        <div class="AuthBox-body">\n          <a class ...
```

I'm not sure if this means there's a successful read of my credentials or not?

How can I post my Rmd file to Confuence?

**Comment by yutannihilation** [comment]
> I'm not sure if this means there's a successful read of my credentials or not?

If you didn't see any popups to input credentials, your credentials are successfully read. But, your result suggests your company have some more auth system in front of Confluence? I have no knowledge about Cloudflare Access...

**Comment by rocanja** [comment]
I am getting the same error trying to post pages on our university wiki space using 'conflr'. It may be an access permission issue as @yutannihilation suspects, but I was wondering whether it could also be an error in how the final URL is compiled under the hood of the conflr functions? I noticed that the base URL of our university's confluence space starts with **https://wiki** instead of the **https://confluence** that is always shown in the examples, not sure if that matters. However, when I define the URL as: `CONFLUENCE_URL="https://wiki.ouruniversityname.edu.au"`, I get the following error `'Error: $ operator is invalid for atomic vectors'` even before I get to the preview. When I specify the URL as `CONFLUENCE_URL="https://wiki.ouruniversityname.edu.au/display"`, the preview is created, but I get the error:
```
Warning: Error in parse_url: length(url) == 1 is not TRUE
  65: <Anonymous>
```

**Comment by rocanja** [comment]
I have raised a ticket with my local IT support team and they have confirmed that 'Integrations such as these would need to be reviewed and approved by the service manager, as there would be work associated around making our authentication on the wiki work to enable this function to generate pages automatically' ... and thus, it is indeed an authentication issue ... too bad, would have loved to use it!

**Comment by yutannihilation** [comment]
Closing this as it seems an authentication problem. Thanks @rocanja for the information.
