### ISSUE TITLE
Error: Timeout was reached

### ISSUE THREAD

**Issue by Liisukas** [line/conflr#115]
I got an error: "Error: Timeout was reached: [confluence.big.local] Connection timed out after 10001 milliseconds" after I inserted a confluence https and my username and password. Could you help with that?

Thank you in advance
Liis

**Comment by yutannihilation** [comment]
It seems you have some network connectivity issue. Does `httr::GET("https://<your confluence domain>/rest/api")` succeed? Or does it fail with the same error?

**Comment by Liisukas** [comment]
Thank you for your reply! It did fail with the same error. I will cooperate with someone who knows about the connectivity.

**Comment by yutannihilation** [comment]
Thanks for confirmation! Then, it's not a conflr-specific problem but a general problem of network settings. You might need to add some setting about proxy (c.f. https://support.rstudio.com/hc/en-us/articles/200488488-Configuring-R-to-Use-an-HTTP-or-HTTPS-Proxy), but in any case you should ask your network admin.
