### ISSUE TITLE
'Error: $ operator is invalid for atomic vectors'

### ISSUE THREAD

**Issue by rocanja** [line/conflr#118]
I just came across 'conflr' today and it's exactly what I have been looking for for so long and thus, I am very excited to try it out. However, when I try to “Post to Confluence”, I get the error: '**Error: $ operator is invalid for atomic vectors**'.

I have tried using the Addin in Rstudio and have also tried running `confl_create_post_from_Rmd()` from R console, but get the same error in both. I have installed pandoc and set the environment variables to point towards its location, which solved the initial 'Error: pandoc version 1.12.3 or higher is required and was not found' problem. I get prompted to enter the confluence url, userid and password, but then the process terminates with the error above, before the document even gets knitted or the preview comes up. I have been using rmarkdown for quite some time and have setup a very small 'hello world' type .rmd file just to test 'conflr'. The file converts just fine when using knit to html. I have no clue what this error may be caused by and was wondering whether it may even be a Confluence access privileges issue, since I am not a System Administrator for the Confluence space I am trying to post to, but I am allowed to create pages through the web interface. Any help would be greatly appreciated.

pandoc-2.10-windows-x86_64
conflr_0.1.1.9000
RStudio: Version 1.2.5033
R version 4.0.0 (2020-04-24)
Platform: x86_64-w64-mingw32/x64 (64-bit)

**Comment by rocanja** [comment]
I got one step further by changing the CONFLUENCE_URL from: `https://wiki.ouruniversityname.edu.au` to `https://wiki.ouruniversityname.edu.au/display/spacekey`. Now I do get the preview, but when I click Publish, I now get the error **Warning: Error in parse_url: length(url) == 1 is not TRUE
 65: <Anonymous>**
which is described in another post, but without a solution ... but likely an access permission issue.

**Comment by rocanja** [comment]
I have raised a ticket with my local IT support team and they have confirmed that ' Integrations such as these would need to be reviewed and approved by the service manager, as there would be work associated around making our authentication on the wiki work to enable this function to generate pages automatically' ... and thus, it is indeed an authentication issue ... too bad, would have loved to use it!

**Comment by yutannihilation** [comment]
Ah, thanks for confirmation (and sorry I couldn't help you...). Yeah, it's not always the case that the Confluence API is allowed to use, sadly... I'm still hoping conflr show a bit friendlier error, but still not sure if it's doable. Anyway, thanks for filing a issue!
