### ISSUE TITLE
Cannot upload LaTex

### ISSUE THREAD

**Issue by harryprince** [line/conflr#12]
I can  not use conflr to upload LaTex.

here is my latex content:

$$ y = \frac {1 }{2}$$

result in wiki:

![image](https://user-images.githubusercontent.com/5362577/52939832-131d9300-33a0-11e9-8012-a5025ebe38f9.png)

it seems that the latex macro is wrong

**Comment by yutannihilation** [comment]
Oh, thanks for the report.

Do you know what plugin your Confluence uses to draw Maths?

**Comment by yutannihilation** [comment]
conflr expects this addon installed. (This should be documented more clearly, sorry...)

https://marketplace.atlassian.com/apps/1210882/latex-math

**Comment by harryprince** [comment]
thanks a lot, I found the problem comes from my own wiki system.
