### ISSUE TITLE
Integration with pkgdown

### ISSUE THREAD

**Issue by slodge** [line/conflr#120]
Has anyone explored the idea of integrating conflr with pkgdown to enable "company internal packages" to have their documentation published within an existing confluence site?

I can see there could be a fair amount of work involved in this - especially in getting intra-document hyperlink references to work - but it's something we're considering looking at right now - so thought I'd ask in case someone's already go this working, or in case someone's already tried it and there were some horrible gotchas which made it impossible.

**Comment by yutannihilation** [comment]
Thanks for the idea, but conflr is a package that converts R Markdown documents to confluence page. OTOH, pkgdown documents are generated from roxygen docs (and others). So, I think this is out of scope of conflr. You might get better answer on RStudio Community.
