### ISSUE TITLE
conflr:::confl_create_post_from_Rmd_addin() leads to error "Warning: Error in parse_url: length(url) == 1 is not TRUE"

### ISSUE THREAD

**Issue by gabesolomon10** [line/conflr#129]
Hello,

I'm very new to this package, but my team is looking to start automatically generating confluence pages in R.  I've set up my .Renviron file correctly (I believe) but when I try to use the addin to send a basic rmarkdown file to our confluence space I get the following:

```
Listening on http://127.0.0.1:7732
Warning: Error in parse_url: length(url) == 1 is not TRUE
  65: <Anonymous>
```

Is this an issue with our confluence settings, or the way I'm using the addin?  Thank you!

**Comment by gabesolomon10** [comment]
I had the wrong login info... Thanks!

**Comment by yutannihilation** [comment]
conflr might be able to display some friendlier error, but, for now, glad that you find a way :)
