### ISSUE TITLE
Update existing page

### ISSUE THREAD

**Issue by adomingues** [line/conflr#131]
Hi @yutannihilation,

I have a question: is it possible to edit an existing page? Or in other other words, retrieve and existing page using `conflr`, make edits and publish with `conflr`.

The use case is when I publish a new page using your add-in (great work!), someone edits the page on confluence, and I want to update my original Rmd with those changes, make my own edits and publish. 

Thank you.

**Comment by yutannihilation** [comment]
Thanks for reporting! You can use `confl_get_page()` to get the content of an existing page, and update it by `confl_update_page()` (c.f. https://line.github.io/conflr/reference/confl_content.html), but..., I guess your question is about how to convert an existing Confluence pate to an Rmd file, right? If so, I think it's out of the current scope of this package.

**Comment by adomingues** [comment]
Hi @yutannihilation,

apologies for the late reply. `confl_get_page()` should be indeed be what I was looking for, but the page content of a page created in Rmd, `$body$storage$value`, appears to be html. So it is not  clear yo me how I update the content and push with `confl_update_page()`. Do I need to change the content of `$body$storage$value` directly? Am I missing something from thej docs?T

hank you for your patience,
António

**Comment by yutannihilation** [comment]
> Do I need to change the content of `$body$storage$value` directly?

Yes, that's what I meant. What's frustrating here is it's NOT an HTML, but a special language based on XML whose specification is described in nowhere. If it were an HTML, maybe we could parse and convert it to a Markdown format (e.g. https://stackoverflow.com/a/41336896), but it's not possible in this case. For Markdown-to-HTML conversion, conflr does best effort to take care of these gaps. The opposite one is what you need to do by yourself, and unfortunately it would not be very easy...

**Comment by adomingues** [comment]
Got it, thank you 👍🏾 
Too bad that confluence makes it so hard to use markdown on it's pages.
