### ISSUE TITLE
How to insert a math equation? 

### ISSUE THREAD

**Issue by joscani** [line/conflr#132]
I have tried

```md
 $Kpi1 = 100 \cdot \dfrac{V_{2}-V_{0}}{V_{0}}$
```

but It's not rendered in confluent. In confluent we have MathJax Inline Equation macro.

**Comment by yutannihilation** [comment]
Sorry, I can't reproduce the issue, it's rendered fine on my Confluence. Could you provide a bit more details e.g. what errors you see, a minimal reproducible Rmd.

**Comment by BenoitFayolle** [comment]
Hello! I have the same issue.

```
---
title: "R Notebook"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: inline
---

 $Kpi1 = 100 \cdot \dfrac{V_{2}-V_{0}}{V_{0}}$
```

Renders a blank confluence page with the following badge at the top :

![image](https://user-images.githubusercontent.com/17967685/120484505-70904f00-c3b3-11eb-90c9-05e99ab2dfb8.png)

Console output : 

```
conflr:::confl_create_post_from_Rmd_addin()


processing file: test.Rmd
  |..................................................................................................................................| 100%
  ordinary text without R code


output file: test.knit.md

/Applications/RStudio.app/Contents/MacOS/pandoc/pandoc +RTS -K512m -RTS test.utf8.md --to commonmark --from markdown+autolink_bare_uris-tex_math_single_backslash-tex_math_dollars-raw_tex --output test.md --standalone --wrap=none 

Listening on http://127.0.0.1:4310

Output created: test.md
```

**Comment by BenoitFayolle** [comment]
My bad, documentation says I need LaTeX Math addon. We don't have it yet. Hopefully solves it for OP
