### ISSUE TITLE
Integrate with `mark`

### ISSUE THREAD

**Issue by januz** [line/conflr#134]
For a Confluence space that I am administering, I am toying with the idea of convincing my group to use only a hierarchy of markdown files living in a Github repo to add and edit the content that is displayed on Confluence.

I was thinking about how we could leverage `conflr` to do this but just came across `mark` (https://github.com/kovetskiy/mark) which was designed for exactly that purpose. As I would like to use `.Rmd` files instead of `.md` files to be able to use R for part of the content (like plots), I am wondering whether I could use the two tools in combination.

For example, would it be possible for `conflr` to output `.md` files that are compatible with `mark` (and use/preserve the syntax elements that `mark` provides) so that one could use `conflr` as a kind of a preprocessor that returns files that can then be synced to Confluence using `mark`?

**Comment by yutannihilation** [comment]
Hi, interesting idea. However, we don't have a development bandwidth to support yet another syntax than that of Confluence itself. I think you can simply write a .Rmd file with mark's metadata into .md. `<!-- -->` should be preserved after the conversion, if I remember correctly. You might need to tweak the result .md with some regex-fu. Wish you a luck :)
