### ISSUE TITLE
Error when trying to publish to confluence

### ISSUE THREAD

**Issue by sebastianmarinc** [line/conflr#135]
Whenever I try to publish to confluence online, I get the following error:
```
Warning: Error in parse_url: length(url) == 1 is not TRUE
65: <Anonymous>
```
I'm not sure what it means. I'm pretty sure my credentials are correct. They would be: 
https://<<domain>>.atlassian.net/wiki/home
username
API password

**Comment by yutannihilation** [comment]
What happens if you change the URL to https://<>.atlassian.net/wiki ?

**Comment by sebastianmarinc** [comment]
It's the same. For context, I'm trying to publish on my employers page. A menu pops up to where I can specify the space and page ID but can't publish.

**Comment by yutannihilation** [comment]
Thanks. 

> username

You need to use email address. Did you try already?

c.f. https://github.com/line/conflr#preparation

**Comment by sebastianmarinc** [comment]
Thanks! I think that published the page but the notebook isn't showing up. I also got: 

> Warning: Error in read_xml.raw: Opening and ending tag mismatch: li line 397 and td [76]
>   56: read_xml.raw
>   55: read_xml.character
>   53: translate_to_confl_macro
>   52: confl_upload
>   51: <observer>
>    8: shiny::runApp
>    7: shiny::runGadget
>    6: <Anonymous>
>    4: output_format$post_processor
>    3: rmarkdown::render
>    2: confl_create_post_from_Rmd
>    1: conflr:::confl_create_post_from_Rmd_addin

**Comment by yutannihilation** [comment]
This

> Error in read_xml.raw: Opening and ending tag mismatch: li line 397 and td [76]

generally says the knitted result is invalid as XML, even though it's valid as HTML. If you are using some package that generates tables, it might be the cause, but there's no way guaranteed to save you from this frustrating error, sorry.

The error occurs here:

https://github.com/line/conflr/blob/3bd5533d4da044c89c5b58af7095d8f517461341/R/translate.R#L55

**Comment by sebastianmarinc** [comment]
Ah ok I see. I have xml2 as a dependency. I'll refactor to see if I can work around this and update shortly.

**Comment by sebastianmarinc** [comment]
It worked after I dropped the dependency. Thanks!

**Comment by yutannihilation** [comment]
Glad it worked for you!
