### ISSUE TITLE
Using conflr does not seem to work well with data.table

### ISSUE THREAD

**Issue by statquant** [line/conflr#14]
I looks like when I use data.table in the Rmd that I want to push on confluence I get issues with data.table. Typically the attributes of the data.table might be messed up.
I add similar issues before when writing my own packages and I had to add Depends: data.table in DESCRIPTION

**Comment by statquant** [comment]
Actually if I copy confl_create_post_from_Rmd and run it locally it works so I'll keep looking for the issue

**Comment by yutannihilation** [comment]
Thanks for the report. Could you provide an example Rmd?

**Comment by yutannihilation** [comment]
@statquant Sorry, I cannot reproduce the problem. I'm closing this issue, but please feel free to add a minimal reproducible example, then I will reopen this. Thanks!
