### ISSUE TITLE
How can I publish R package documentation to confluence

### ISSUE THREAD

**Issue by de-mim-1974** [line/conflr#144]
In our department we have created some R packages. We would now like to publish the roxygen documentation of the packages in our Confluence space. Unfortunately roxygen only creates .RD files and pkgdown only creates web (html, css, js) output.

Do you have any solution for this requirement?

**Comment by yutannihilation** [comment]
I think you can convert your .rd files to markdown files by [roxygen2md](https://roxygen2md.r-lib.org/), then maybe you can publish the markdown to your Confluence?

**Comment by de-mim-1974** [comment]
Thanks for your tip. The [roxygen2md](https://roxygen2md.r-lib.org/) package converts the .Rd style annotations to Markdown style annotations in the roxygen documentation of functions in the R Code files.
Unfortunately, no md or rmd files are created.

**Comment by yutannihilation** [comment]
Ah, sorry, I referred to a wrong package... What was in my mind was this one. Does this work for you?

https://github.com/quantsch/Rd2md

**Comment by yutannihilation** [comment]
Closing this as this usage is out of scope of conflr itself, sorry. Feel free to file a new issue if you have more questions!
