### ISSUE TITLE
conflr with Plotly

### ISSUE THREAD

**Issue by MadsTrolle** [line/conflr#15]
Plotly is a great and versatile plotting tool for R, especially in R markdown. 

I think conflr does not currently support plotly graphs...

However, this would be a fantastic addition to an awesome and much needed tool!

**Comment by yutannihilation** [comment]
I think Confluence doesn't allow you to embed plot.ly. Can you?

**Comment by MadsTrolle** [comment]
I guess there is no easy way of embedding the plotly JavaScript object in confluence… Will look a bit more into if that's possible

A simple workaround would be turning the plotly item into a png, that's then included in the markdown like below.

`
```{r pressure, echo=FALSE, include=FALSE}
p = plotly::plot_ly(pressure, x = ~temperature, y = ~pressure, mode = 'type', type = 'scatter')
plotly::orca(p, "tmp.png")
```
```{r}
knitr::include_graphics("tmp.png")
```
`

The above deploys the image to our company confluence page using conflr. Not a pretty solution, though… And would require an installation of the orca command line program on the user side https://github.com/plotly/orca and version

**Comment by yutannihilation** [comment]
Thanks. FYI, if you are OK with the screenshots, using webshot is more handy.

https://bookdown.org/yihui/bookdown/html-widgets.html

For example, this should work (after you install PhantomJS by `webshot::install_phantomjs()`):

```` md
---
title: "plot.ly test"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  screenshot.force = TRUE
)
```

## plot.ly test

```{r plotly}
library(plotly)

plot_ly(economics, x = ~pop)
```
````

**Comment by MadsTrolle** [comment]
Excellent advice - many thanks!

**Comment by statquant** [comment]
FYI some people in my company are using plotly in confluence and it is totally reactive. People put things in an iframe to make it work

**Comment by statquant** [comment]
![image](https://user-images.githubusercontent.com/3612473/55166625-5f11e380-5167-11e9-9a87-4487e135f299.png)
![image](https://user-images.githubusercontent.com/3612473/55166670-751fa400-5167-11e9-82fe-eb7ed3121c28.png)

**Comment by yutannihilation** [comment]
Yeah, if HTML macro is available, it's possible. But, I don't think it's not always the case.

> HTML macros are disabled by default
https://confluence.atlassian.com/doc/html-macro-38273085.html

Unfortunately, I don't have access to a Confluence with HTML macro enabled... Do you want to try a PR for this feature?

**Comment by arisehkawamura** [comment]
@statquant 
Can you share us the full HTML code?

**Comment by statquant** [comment]
Hello @yutannihilation if you can drive me a bit I'd like to try to PR this, I think that would really make a huge difference to this package and our work flow in general. I have access to confluence with html macro

**Comment by yutannihilation** [comment]
A PR for this will be really appreciated!

**Comment by statquant** [comment]
Would you have some tips and pointers to get me started ?

**Comment by yutannihilation** [comment]
Sorry, I don't have much time to write some developer guide... I guess you can add something like `replace_htmlwidgets()` in this function:

https://github.com/line/conflr/blob/38143bb8920cebcf7e20e61186c070a5b2bc14fa/R/translate.R#L12
