### ISSUE TITLE
Is it possible to programmatically untick "notify watchers" when posting to confluence?

### ISSUE THREAD

**Issue by timschoof** [line/conflr#150]
Thanks for creating such a great package! I've been using it a lot and may have been spamming my colleagues a bit too much lately. Is there perhaps a way to untick the "notify watchers" button when you edit the page programmatically using conflr (e.g. when using confl_create_post_from_Rmd())? Thanks!
![image](https://user-images.githubusercontent.com/4145334/159527249-ed39a3d5-b2e3-4d4e-b200-efb1677c1f17.png)

**Comment by timschoof** [comment]
That worked. Thanks so much, @yutannihilation!

**Comment by yutannihilation** [comment]
Great!
