### ISSUE TITLE
403 forbidden

### ISSUE THREAD

**Issue by stefanoallima** [line/conflr#153]
I was trying to post a rmarkdown but recently i got the following error
i executed the following:
`rlang::last_trace()`

output end of blob
```
<!-- .aui-page-header-inner --></header><!-- .aui-page-header --><div class="aui-message aui-message-warning warning">
                            <p>Encountered a <code>"403 - Forbidden"</code> error while loading this page.</p>
                            <p><a href="/secure/MyJiraHome.jspa">Go to Jira home</a></p>
                        </div>
                </section><!-- .aui-page-panel-content -->
</div>
<!-- .aui-page-panel-inner -->
</div>
<!-- .aui-page-panel -->
</body>
</html>
```

Backtrace:
     ▆
  1. └─conflr:::confl_create_post_from_Rmd_addin()
  2.   └─conflr::confl_create_post_from_Rmd(Rmd_file, interactive = TRUE)
  3.     └─rmarkdown::render(...)
  4.       └─output_format$pre_knit(input = original_input)
  5.         ├─base::tryCatch(...)
  6.         │ └─base tryCatchList(expr, classes, parentenv, handlers)
  7.         │   └─base tryCatchOne(expr, names, parentenv, handlers[[1L]])
  8.         │     └─base doTryCatch(return(expr), name, parentenv, handler)
  9.         └─conflr::confl_get_current_user()
 10.           └─conflr:::confl_verb("GET", "/user/current", query = purrr::compact(query))
 11.             └─rlang::abort(...)

**Comment by yutannihilation** [comment]
Hi, is `CONFLUENCE_URL` configured correctly?

**Comment by stefanoallima** [comment]
Thanks for following up.
i added the wiki and it solved my issue

/wiki

https://company_domain.atlassian.net**/wiki**

**Comment by yutannihilation** [comment]
Great! It's a common pitfall on Atlassian Cloud.
