### ISSUE TITLE
scrollbars on wide tables?

### ISSUE THREAD

**Issue by fkgruber** [line/conflr#165]
Is it possible to add some sort of html code or something that could make the tables show scrollbars when they are wide? I know that confluence can do that if you create the table manually.
thanks
FKG

**Comment by yutannihilation** [comment]
Hi, I think this is the same issue as https://github.com/line/conflr/issues/137, and this is not possible with conflr, unfortunately.

cf., https://github.com/line/conflr/issues/137#issuecomment-950136015.

Quarto might help because it should use the new editor.
