### ISSUE TITLE
Images displayed on "large" size instead of original

### ISSUE THREAD

**Issue by ndiquattro** [line/conflr#21]
First off, thanks for your work on this package, I'm very excited about it!

After trying to upload a page, I noticed that all the images were resized to "large" in confluence causing them to become unreadable/not match the preview. Is it possible to set them to display at "original" size without manually editing the page?

Thanks!

**Comment by yutannihilation** [comment]
Thanks for the idea! I agree conflr needs an option for this.

In the meantime, you can set `out.height` to get larger images.

```` md
```{r out.height='600px'}
plot(1)
```
````

**Comment by yutannihilation** [comment]
@ndiquattro 
I added an option "Use original image sizes" to control this. Could you try and confirm this solves your problem?

**Comment by ndiquattro** [comment]
@yutannihilation I tried it out and it works! Thanks so much for the fast update!

**Comment by yutannihilation** [comment]
Thanks for testing!
