### ISSUE TITLE
Disables some data.table functionality

### ISSUE THREAD

**Issue by jzzcutler** [line/conflr#29]
Hi,  
  I really like the project by the way.  Thank you very much for sharing it.  You had a data.table issue a while back that you couldn't recreate so I've supplied a sample that fails.

  I've attached a txt file - just change the extension to .rmd.  The data.table operations work under knitr but fail under conflr saying that dt is not a data.table.

[TestDataTable.txt](https://github.com/line/conflr/files/3084794/TestDataTable.txt)

**Comment by jzzcutler** [comment]
data.table version: 1.12.2
conflr version: 0.0.5.9000

**Comment by yutannihilation** [comment]
Thanks, confirmed. It seems things are more complicated than I thought... Let me think a bit more about what happens here.

https://stackoverflow.com/a/13113174

**Comment by yutannihilation** [comment]
@jzzcutler I believe now conflr can knit documents containing `data.table`. Could you confirm when you have time?
