### ISSUE TITLE
How to authenticate in Atlassian Cloud?

### ISSUE THREAD

**Issue by daranzolin** [line/conflr#3]
This is exciting!

But per Atlassian, [usernames are no longer a thing in Atlassian Cloud.](https://confluence.atlassian.com/cloud/blog/2018/06/say-goodbye-to-usernames-in-atlassian-cloud) Is it still possible to authenticate with `conflr`? If so, how?

**Comment by yutannihilation** [comment]
Thanks for the notice! I have zero knowledge about the Atlassian Cloud. Do you know how we can get authenticated there?

**Comment by yutannihilation** [comment]
It seems you can use your email address for username, and API token for password. Could you try?

https://confluence.atlassian.com/cloud/api-tokens-938839638.html

**Comment by perceptron01** [comment]
I tried using my email address for username, and API token for password. 
But authentication failed and I received the following message. 
`> conflr:::confl_create_post_from_Rmd()`
`Error in confl_verb("GET", "/user/current", query = purrr::compact(query)) : 
  Error in stop(httr::http_condition(res, type = "error"), httr::content(res)): Not Found (HTTP 404).
null for uri: https://<base_url>/rest/api/user/current404
In addition: Warning message:
In stop(e, call. = FALSE) : additional arguments ignored in stop()`

**Comment by yutannihilation** [comment]
Thanks for the error details! It seems you need to specify `/wiki` (i.e. `https://<your-domain>.atlassian.net/wiki`) in addition to the base URL of your Atlassian Cloud. Could you try again with this?

c.f. https://developer.atlassian.com/cloud/confluence/rest/#api-user-current-get

**Comment by perceptron01** [comment]
Thanks for the comment! After fixing, I succeeded in creating pages.

**Comment by yutannihilation** [comment]
OK, I'm gradually understanding... Thanks for your help. In summary, on Atlassian Cloud, 

* base URL is `https://<your-domain>.atlassian.net/wiki`
* username is your email address
* password is your API token, which you can issue at https://id.atlassian.com (c.f. https://confluence.atlassian.com/cloud/api-tokens-938839638.html)

**Comment by daranzolin** [comment]
Worked for me too! Thanks!

**Comment by yutannihilation** [comment]
Thanks for conformation! Then, I'll close this after improving README 👍
