### ISSUE TITLE
Hide warning about missing personal space

### ISSUE THREAD

**Issue by halldc** [line/conflr#30]
The default value of the Shiny UI component for the Confluence space is the user's personal space. The conflr package attempts to use the username as the space key, but personal spaces often a numeric space key ([see here](https://community.atlassian.com/t5/Confluence-questions/Why-is-the-Personal-space-key-a-numeric-key-instead-of-name/qaq-p/777508)). 

It would be good to suppress the warning message like:
```
Warning message:
In confl_verb("GET", glue::glue("/space/{spaceKey}"), query = purrr::compact(query)) :
  Error in stop(httr::http_condition(res, type = "error"), httr::content(res)): Not Found (HTTP 404).
404list(authorized = FALSE, valid = TRUE, errors = list(), successful = FALSE)No space found with key : ~david.hall
```

**Comment by yutannihilation** [comment]
Thanks, agreed.

**Comment by yutannihilation** [comment]
@halldc Now the warning should be suppressed. Could you try when you have time?
