### ISSUE TITLE
confluence_document

### ISSUE THREAD

**Issue by yutannihilation** [line/conflr#51]
Probably we can do this by setting some `post_processor`.

``` md
---
title: "foo"
output:
  confluence_document:
    space_key: "my_space"
    parent_id: "123456789"
    ...
---
```

**Comment by andrewcstewart** [comment]
This is a fantastic idea.  Want some help with it?  

Looks like the _basic_ idea would be something like this...

```
post_processor <- function(metadata, input_file, output_file, clean, verbose) {
   ...
   confl_create_post_from_Rmd(Rmd_file = outout_file)
}
```

**Comment by yutannihilation** [comment]
Thanks, yes, I guess it would be something using `post_processor`. But, I feel I need to refactor the internals around `confl_create_post_from_Rmd ()` before adding new features. So, please wait for a while...

**Comment by andrewcstewart** [comment]
Sounds good.  I may stitch together a basic experiment using `confl_create_post_from_Rmd` just to see if any other potential issues shake out.

**Comment by yutannihilation** [comment]
> But, I feel I need to refactor the internals around `confl_create_post_from_Rmd ()` before adding new features.

Refactoring is done! (#61)

**Comment by andrewcstewart** [comment]
@yutannihilation - That's awesome.  What's the implication for a potential `confluence_document` ?

**Comment by andrewcstewart** [comment]
I think I've got a basic prototype worked out:

```
library(rmarkdown)
library(knitr)

pre_knit <- function(input_file) {
  conflr::confl_create_post_from_Rmd(Rmd_file = input_file, space_key=NULL)
}

confluence_document <- output_format(knitr = knitr_options(opts_chunk = list(dev = 'png')),
              pandoc = pandoc_options(to = "html"),
              pre_knit = pre_knit)
              # post_processor = post_processor)
```

`confluence_document` could then be used in `rmarkdown::render`...

```
render("Untitled.Rmd", confluence_document)
```
Or used in the YAML header of the Rmd file...

```
---
title: "foo"
output:
  confluence_document
---
```

Need to figure out the best way to access the yaml header options (like in your first example).

**Comment by andrewcstewart** [comment]
Actually, all of that could be combined into a single function, like so:

```
confluence_document <- function(...) {
  
  pre_knit <- function(input_file) {
    front_matter <- rmarkdown::yaml_front_matter(input_file, "UTF-8")
    conflr::confl_create_post_from_Rmd(Rmd_file = input_file, 
                                       # space_key="~308662965",
                                       params=front_matter$output$confluence_settings,
                                       update=TRUE,
                                       interactive = FALSE)
  }
  
  format <- output_format(knitr = knitr_options(opts_chunk = list(dev = 'png')),
                pandoc = pandoc_options(to = "html"),
                pre_knit = pre_knit)
  return(format)
}
```

I feel like this may actually just be a variant of `confl_create_post_from_Rmd`.

**Comment by yutannihilation** [comment]
Thanks for the idea! But I think it should be `post_processor` rather than `pre_knit`, which probably requires me to refactor more by separating this part to another function.

https://github.com/line/conflr/blob/3795b20b08ed25ead12d76ca3c2e6d739f7f36cf/R/addin.R#L126-L170

**Comment by yutannihilation** [comment]
I mean, it's not that `confluence_ducment()` will use `confl_create_post_from_Rmd()` inside, but `confl_create_post_from_Rmd()` will use `confluence_ducment()`. Sorry, this will be bigger change than I expected at first... while I'd really appreciate if you tackle this issue, probably this is what I should take care of as some internals need to be tweaked.

**Comment by yutannihilation** [comment]
Implemented in #77

**Comment by andrewcstewart** [comment]
This is amazing.  I just ran a couple tests with it and it works really well.

**Comment by yutannihilation** [comment]
Thanks for testing!
