### ISSUE TITLE
Broken image link on the website

### ISSUE THREAD

**Issue by cderv** [line/conflr#53]
I got that 
![image](https://user-images.githubusercontent.com/6791940/70914549-7f950d00-2018-11ea-9e3f-1109dbad4da2.png)

on your pkgdown website https://line.github.io/conflr/

**Comment by yutannihilation** [comment]
Oops..., thanks for the notice!

**Comment by yutannihilation** [comment]
Fixed :)

<img width="1102" alt="スクリーンショット 2019-12-17 13 40 03" src="https://user-images.githubusercontent.com/1978793/70965368-c9422e00-20d2-11ea-800c-3c5ef099c93d.png">
