### ISSUE TITLE
Add support for language option in confluence code block macro

### ISSUE THREAD

**Issue by cderv** [line/conflr#54]
Currently, it seems the language of an rmarkdown code chunk is lost in translation between the Rmd to md conversion, and then can't be reported to html conversion, and finally confluence post processing of html to create xml storage format. 

However, it is possible to add the option to code block macro using
```xml
<ac:structured-macro ac:name="code">
  <ac:parameter ac:name="language">r</ac:parameter>
  <ac:plain-text-body><![CDATA[this is my code]]></ac:plain-text-body>
</ac:structured-macro>
```
https://confluence.atlassian.com/conf59/code-block-macro-792499083.html#CodeBlockMacro-Storageformatexample

I think it could be possible to add such support. I can look into it, but first what do you think ? 
Did you already try something ? 

Thanks.

**Comment by yutannihilation** [comment]
Thanks, I didn't consider about this option (for a reason, I wrote below).

> first what do you think ?

I think it's possible. Probably the loss of `language` is simply due to my lack of the knowledge about Pandoc's options... Do you know the right one to add here?

https://github.com/line/conflr/blob/1d474afa442a7bf696ece7331bba88e6fe3d21c7/R/addin.R#L59-L71

Or, even if the corresponding option cannot be used for some reason, we can mark the `language` option before converting it to md and restore the option after the conversion (I learnt this technique from formatR).

One thing I'm not sure is how Confluence handles the language option when the syntax highlight is not available. On my environment, it seems syntax highlighting of R is not supported (that's why I didn't think this option matters). Does your Confluence's code block support R?

**Comment by cderv** [comment]
> Do you know the right one to add here?

I'll look into it, I think of some option that could work, but it may come from the markdown_strict format also. I don't know if this format support code with language attributes for highlight. I'll try.

To fully understand the design, why converting to markdown_strict using pandoc, then html using commonmak ? Is there a specific reason or a custom pandoc template for html would work ? I guess it is linked to #51 where a custom Rmarkdown format is discussed.

> Does your Confluence's code block support R?

Not by default. I asked my confluence admin to add support for R language. You can easily define a new language
https://confluence.atlassian.com/doc/code-block-macro-139390.html#CodeBlockMacro-ConfiguretheCodeBlockmacro
It is using the [brush syntax](http://alexgorbatchev.com/SyntaxHighlighter/manual/brushes/custom.html)  and I found on example to play with on the web in yihui's gist https://gist.github.com/yihui/1804862 - I used this one even if it is old but it works fine. I am sure it can be improve but I did not modify it yet. This could be another thing to work together. 
I think a vignette could be added on how to configure confluence for this and those brush syntax related file could be included in the package for example.

> One thing I'm not sure is how Confluence handles the language option when the syntax highlight is not available.

You are right, This is the drawback - I think confluence does not render code block correctly if language is unknown It does not default to one language. 
I guess there should be an option in this package to opt-in or opt-out, depending which default behaviour you choose. 

When we began with confluence, this was one of the first thing I looked into - how to get syntax highlighting correct for R chunk?
The second was : how to publish my Rmd directly as confluence page ? I was very happy to found your 📦 ! Works very well! but my 'first thing' is now missing as not R highlights.

**Comment by yutannihilation** [comment]
> Works very well! but my 'first thing' is now missing as not R highlights.

Oh..., thanks for your context! I see.

> To fully understand the design, why converting to markdown_strict using pandoc, then html using commonmak ?

This is mainly in order to preview the page on RStudio; for previewing, RStudio requires base64-encoded images, but for posting to Confluence, we need paths to the image files. So, I found it convenient to generate an intermediate md and modify it in two ways.

Other small reasons I don't remember are related to the fact that the syntax of Confluence is not valid either as HTML or as XML. I struggled to tweak the document by heavily using xml2, but it sometimes errored and then I found using commonmark just works. 

(#51 is just for convenience. e.g. Writing the page ID on the Rmd might make it easy to update a specific Confluence page periodically)

**Comment by yutannihilation** [comment]
FWIW, it seems users see this error if the `language` is not supported on their Confluence.

<img width="635" alt="スクリーンショット 2019-12-19 12 56 13" src="https://user-images.githubusercontent.com/1978793/71143754-04716800-225f-11ea-863d-b6bd413ed350.png">

**Comment by yutannihilation** [comment]
I found why the `language` is lost... The default variant of `md_document()` is the original Markdown syntax (`markdown_strict`). It defines only "indented code block" and there's no "fenced code block":

https://daringfireball.net/projects/markdown/syntax#precode

So, it might be as easy as just specifying `variant = "gfm"`, but I don't remember if I tried this (and failed?).

**Comment by cderv** [comment]
> FWIW, it seems users see this error if the language is not supported on their Confluence.

Thanks ! That mean an opt-in mechanism can be required to activate only for those who have R language support. Some helpers and a vignette to add this support can be useful. 

> The default variant of md_document() is the original Markdown syntax (markdown_strict)

This is what I thought. Is it not possible to activate fenced code block with `+fenced_code_blocks` ? 
You maybe use pandoc markdown using `markdown` or maybe `commonmark` as you use it after ? This is a pandoc output format. 

I'll try to look into it today.

**Comment by yutannihilation** [comment]
> You maybe use pandoc markdown using `markdown` or maybe `commonmark` as you use it after ? This is a pandoc output format.

Oh, thanks! I didn't know these variants. `+fenced_code_blocks` doesn't work, but `markdown` and `commonmark` works fine.

```` console
$ echo -e '``` r\n1 + 1\n```' > tmp.md
$ pandoc --to markdown_strict+fenced_code_attributes tmp.md 
    1 + 1
$ pandoc --to markdown tmp.md 
``` {.r}
1 + 1
```
$ pandoc --to commonmark tmp.md 
``` r
1 + 1
```
````

**Comment by cderv** [comment]
You have a really wide variety of output format 
https://pandoc.org/MANUAL.html#general-options

Since last pandoc you even have a JIRA markup format !!! Dev reprex use it now I think. but I am not sure it works for confluence. May be it is worth the try though?

**Comment by yutannihilation** [comment]
Hmm..., it seems [Confluence's REST API](https://docs.atlassian.com/ConfluenceServer/rest/7.2.0/#api/content-createContent) doesn't accept markup documents directly and probably we need to convert it to storage format beforehand. But, it might be cleaner than the current implementation.

c.f. https://developer.atlassian.com/server/confluence/confluence-rest-api-examples/

**Comment by yutannihilation** [comment]
Sorry, conflr's internals are messy and probably I don't have enough time to explain how to develop this feature... so instead I created a naive implementation (no fallback is considered at the moment) for illustration: https://github.com/line/conflr/pull/55

**Comment by yutannihilation** [comment]
@cderv 
I updated #55 with an opt-in by setting `options(conflr_supported_languages_extra = "r")`. Could you try when you have time? I'm not yet sure if it's a good idea to pass this via option, though. Any suggestions are welcome!

**Comment by cderv** [comment]
Thanks ! 

I can try at work beginning of January next year. 

Option is not so bad for an opt-in mechanism. In your translation process I think you may catch a language not in your default language and throws a message or a warning once that is the user want to have R highlighting in confluence, one should configures with its confluence admin then modifies option in R. Maybe it is not necessary and only users who will read the doc will know about this and its enough. 😄 

Other solution I see is to add extra supported languages as an argument in your user-facing functions. I would imagine having to provide as function argument when posting (like venue in reprex).  And if I want to set it up globally i would set up the option to change the default.  

That make me thinks that we could ask confluence if they are willing to add R in the default language... I don't know how though... 🤔

**Comment by yutannihilation** [comment]
> I can try at work beginning of January next year.

Aw, sorry for disturbing you...

Thanks, I'll consider warnings. Sounds reasonable. For making it as an argument, I'm yet to see how to pass them, but I think I'll come up with some idea next year...

Have a nice holiday!

**Comment by cderv** [comment]
> Aw, sorry for disturbing you...

Oh you are not disturbing at all !  
Unfortunately, I do most of my open source activities on my time off. 😉

It just I won’t have a confluence website to test with until next year. 🤷‍♂️

**Comment by yutannihilation** [comment]
Oh, I see, thanks :)
