### ISSUE TITLE
Unexpected close tag?

### ISSUE THREAD

**Issue by andrewcstewart** [line/conflr#56]
Getting an error when trying to publish.  Not sure if related to https://github.com/line/conflr/issues/45 ?

```
Listening on http://127.0.0.1:7685
Warning: Error in confl_verb: Error in stop(httr::http_condition(res, type = "error"), httr::content(res)): Bad Request (HTTP 400).
400list(authorized = FALSE, valid = TRUE, errors = list(), successful = FALSE)com.atlassian.confluence.api.service.exceptions.BadRequestException: Error parsing xhtml: Unexpected close tag </ac:structured-macro>; expected </p>.
 at [row,col {unknown-source}]: [22,21]
  78: stop
  77: confl_verb
  76: confl_update_page
  75: observeEventHandler
   4: shiny::runApp
   3: shiny::runGadget
   2: confl_addin_upload
   1: conflr::confl_create_post_from_Rmd
```

**Comment by andrewcstewart** [comment]
I think I figured out the problem here.  Apparently `$`'s somehow breaks the conversion process.

**Comment by yutannihilation** [comment]
Since `$` is used as a beginning and ending delimiter of a MathJax block, unpaired `$` causes this kind of error. I guess escaping the sign (`\$`) should work. If not, could you provide a reprex?

**Comment by andrewcstewart** [comment]
Closing this out since I figured it out.

**Comment by yutannihilation** [comment]
Sure. It might be nice to show some friendly error for this tag (`$`) mismatch, so probably I'll tackle this problem in future.
