### ISSUE TITLE
URL from published page no longer returned

### ISSUE THREAD

**Issue by ndiquattro** [line/conflr#95]
Hello!

It looks like `confl_create_post_from_Rmd()` no longer returns the URL of the published page? Is there a way to get that URL still? I was sending it along with an alert that a page was published.

Thanks!

**Comment by yutannihilation** [comment]
Ouch... Sorry, during the recent

**Comment by yutannihilation** [comment]
I think I can record this `results_url` to some environment and acquire the value later. Anyway, I'll fix this somehow. Sorry for the inconvenience!

https://github.com/line/conflr/blob/4dd5f9dbeee20b4f9630cadf0fcd75852b02cc7a/R/addin-internals.R#L132

**Comment by ndiquattro** [comment]
I see, thanks for the information! It's nice to know it's not just my setup.

I do like that you can put the confluence settings in the yaml header now, so I I guess its worth the tradeoff.

As an idea, could be nice to have a more generic `confl_get_url()` that will return the URL for some page id or something and have `cofl_create_post_from_Rmd()` return the required ID.

**Comment by yutannihilation** [comment]
@ndiquattro 
Now `confl_create_post_from_Rmd()` returns the URL again. Returning the page ID sounds a nice idea, but I'm not confident if it's the right interface. If you feel the ID is better than the URL, could you open a new issue with some example? It's not so hard to make a change.

**Comment by ndiquattro** [comment]
Thanks for the quick action @yutannihilation ! I think this will do nicely.
